export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const SORT_PROJECT = "SORT_PROJECT";
export const SEARCH_PROJECTS = "SEARCH_PROJECTS";
